name = "Pixelmon Gear Shift"
author = "MsKarmagick, Big Barza, Kyoki, ProvidenceDaemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0cfa200668dc3990e5ea749027f3b894ee8cf47b4de54d02605f94dee24adbd"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
