name = "Pixelmon Gear Shift"
author = "MsKarmagick, Big Barza, Kyoki, ProvidenceDaemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "430eec2036ffa2f5d229f415651caaf573354cc9bcc8a0bc1359b5d2217c8e7f"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
