name = "Pixelmon Gear Shift"
author = "MsKarmagick, Big Barza, Kyoki, ProvidenceDaemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d97abd7baa97392ecbe534e9e6c3d836cceb0939eae9563d943f623b6b640bee"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
