name = "Pixelmon Gear Shift"
author = "MsKarmagick, Big Barza, Kyoki, ProvidenceDaemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25a3813d2d7ce9257cb9085a40cd3a9a807a5c2e70b499e34b37e324d6f2bd0f"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
