name = "Pixelmon Gear Shift"
author = "MsKarmagick, Big Barza, Kyoki, ProvidenceDaemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20822d42c751db0a22d1f82be3963295015f798afff1d285432ad418048de81e"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
