name = "Pixelmon Gear Shift"
author = "MsKarmagick, Big Barza, Kyoki, ProvidenceDaemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "031951af4778a60f70c45dddd6f16dd5f3fe54b7216309f79049ee2547c83f8c"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
