name = "Pixelmon Gear Shift"
author = "MsKarmagick, Big Barza, Kyoki, ProvidenceDaemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78790a2bea7ef77175b8e7e8d7f9ce724ef6eab711ef59ab121d9340607aecae"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
