name = "Pixelmon Gear Shift"
author = "MsKarmagick, Big Barza, Kyoki, ProvidenceDaemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adbc2dd44fdd1da0db6210dd77b30e2091424c4ae689ae110deb04d8fc43ff1a"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
