name = "Pixelmon Gear Shift"
author = "MsKarmagick, Big Barza, Kyoki, ProvidenceDaemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67d22b54ae0875485f50f5942763c6957973681e2b748f0c9addad8a76ac1d95"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
