name = "Pixelmon Gear Shift"
author = "MsKarmagick, Big Barza, Kyoki, ProvidenceDaemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7180ec9617dd64f6013b9699c57a5793f87c7597d91686f1fb512790ccb261e3"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
